data = {
    "Avon": {
        "2020": {
            "Chimney Fires": 47,
            "Due to apparatus": 1986,
            "Dwellings": 502,
            "Good intent": 1460,
            "Malicious": 78,
            "Non-fire false alarms": 161,
            "Non-fire incidents": 2806,
            "Other Buildings": 220,
            "Other Outdoors": 125,
            "Road Vehicles": 391,
            "Secondary Fires": 1278
        },
        "2021": {
            "Chimney Fires": 35,
            "Due to apparatus": 2407,
            "Dwellings": 522,
            "Good intent": 1226,
            "Malicious": 103,
            "Non-fire false alarms": 234,
            "Non-fire incidents": 3552,
            "Other Buildings": 217,
            "Other Outdoors": 103,
            "Road Vehicles": 446,
            "Secondary Fires": 1414
        },
        "percentage_change": {
            "Chimney Fires": -25.53,
            "Due to apparatus": 21.2,
            "Dwellings": 3.98,
            "Good intent": -16.03,
            "Malicious": 32.05,
            "Non-fire false alarms": 45.34,
            "Non-fire incidents": 26.59,
            "Other Buildings": -1.36,
            "Other Outdoors": -17.6,
            "Road Vehicles": 14.07,
            "Secondary Fires": 10.64
        }
    },
    "Bedfordshire": {
        "2020": {
            "Chimney Fires": 24,
            "Due to apparatus": 1577,
            "Dwellings": 337,
            "Good intent": 847,
            "Malicious": 55,
            "Non-fire false alarms": 84,
            "Non-fire incidents": 1886,
            "Other Buildings": 133,
            "Other Outdoors": 73,
            "Road Vehicles": 183,
            "Secondary Fires": 848
        },
        "2021": {
            "Chimney Fires": 26,
            "Due to apparatus": 1883,
            "Dwellings": 283,
            "Good intent": 689,
            "Malicious": 98,
            "Non-fire false alarms": 112,
            "Non-fire incidents": 2531,
            "Other Buildings": 164,
            "Other Outdoors": 63,
            "Road Vehicles": 235,
            "Secondary Fires": 816
        },
        "percentage_change": {
            "Chimney Fires": 8.33,
            "Due to apparatus": 19.4,
            "Dwellings": -16.02,
            "Good intent": -18.65,
            "Malicious": 78.18,
            "Non-fire false alarms": 33.33,
            "Non-fire incidents": 34.2,
            "Other Buildings": 23.31,
            "Other Outdoors": -13.7,
            "Road Vehicles": 28.42,
            "Secondary Fires": -3.77
        }
    },
    "Berkshire": {
        "2020": {
            "Chimney Fires": 37,
            "Due to apparatus": 2042,
            "Dwellings": 330,
            "Good intent": 1146,
            "Malicious": 55,
            "Non-fire false alarms": 107,
            "Non-fire incidents": 1707,
            "Other Buildings": 161,
            "Other Outdoors": 29,
            "Road Vehicles": 237,
            "Secondary Fires": 911
        },
        "2021": {
            "Chimney Fires": 46,
            "Due to apparatus": 2476,
            "Dwellings": 365,
            "Good intent": 942,
            "Malicious": 96,
            "Non-fire false alarms": 154,
            "Non-fire incidents": 2223,
            "Other Buildings": 180,
            "Other Outdoors": 21,
            "Road Vehicles": 223,
            "Secondary Fires": 712
        },
        "percentage_change": {
            "Chimney Fires": 24.32,
            "Due to apparatus": 21.25,
            "Dwellings": 10.61,
            "Good intent": -17.8,
            "Malicious": 74.55,
            "Non-fire false alarms": 43.93,
            "Non-fire incidents": 30.23,
            "Other Buildings": 11.8,
            "Other Outdoors": -27.59,
            "Road Vehicles": -5.91,
            "Secondary Fires": -21.84
        }
    },
    "Buckinghamshire": {
        "2020": {
            "Chimney Fires": 39,
            "Due to apparatus": 2186,
            "Dwellings": 291,
            "Good intent": 516,
            "Malicious": 62,
            "Non-fire false alarms": 93,
            "Non-fire incidents": 2512,
            "Other Buildings": 146,
            "Other Outdoors": 114,
            "Road Vehicles": 244,
            "Secondary Fires": 1083
        },
        "2021": {
            "Chimney Fires": 48,
            "Due to apparatus": 2302,
            "Dwellings": 332,
            "Good intent": 491,
            "Malicious": 99,
            "Non-fire false alarms": 69,
            "Non-fire incidents": 2986,
            "Other Buildings": 199,
            "Other Outdoors": 87,
            "Road Vehicles": 259,
            "Secondary Fires": 870
        },
        "percentage_change": {
            "Chimney Fires": 23.08,
            "Due to apparatus": 5.31,
            "Dwellings": 14.09,
            "Good intent": -4.84,
            "Malicious": 59.68,
            "Non-fire false alarms": -25.81,
            "Non-fire incidents": 18.87,
            "Other Buildings": 36.3,
            "Other Outdoors": -23.68,
            "Road Vehicles": 6.15,
            "Secondary Fires": -19.67
        }
    },
    "Cambridgeshire": {
        "2020": {
            "Chimney Fires": 30,
            "Due to apparatus": 2150,
            "Dwellings": 276,
            "Good intent": 1169,
            "Malicious": 41,
            "Non-fire incidents": 1387,
            "Other Buildings": 228,
            "Other Outdoors": 65,
            "Road Vehicles": 260,
            "Secondary Fires": 874,
            "Non-fire false alarms": 24
        },
        "2021": {
            "Chimney Fires": 32,
            "Due to apparatus": 2659,
            "Dwellings": 286,
            "Good intent": 1137,
            "Malicious": 47,
            "Non-fire false alarms": 63,
            "Non-fire incidents": 1851,
            "Other Buildings": 216,
            "Other Outdoors": 84,
            "Road Vehicles": 288,
            "Secondary Fires": 976
        },
        "percentage_change": {
            "Chimney Fires": 6.67,
            "Due to apparatus": 23.67,
            "Dwellings": 3.62,
            "Good intent": -2.74,
            "Malicious": 14.63,
            "Non-fire false alarms": 162.5,
            "Non-fire incidents": 33.45,
            "Other Buildings": -5.26,
            "Other Outdoors": 29.23,
            "Road Vehicles": 10.77,
            "Secondary Fires": 11.67
        }
    },
    "Cheshire": {
        "2020": {
            "Chimney Fires": 75,
            "Due to apparatus": 1903,
            "Dwellings": 379,
            "Good intent": 1296,
            "Malicious": 66,
            "Non-fire false alarms": 212,
            "Non-fire incidents": 2126,
            "Other Buildings": 185,
            "Other Outdoors": 89,
            "Road Vehicles": 246,
            "Secondary Fires": 1397
        },
        "2021": {
            "Chimney Fires": 49,
            "Due to apparatus": 1992,
            "Dwellings": 349,
            "Good intent": 1148,
            "Malicious": 84,
            "Non-fire false alarms": 200,
            "Non-fire incidents": 2463,
            "Other Buildings": 219,
            "Other Outdoors": 68,
            "Road Vehicles": 287,
            "Secondary Fires": 1411
        },
        "percentage_change": {
            "Chimney Fires": -34.67,
            "Due to apparatus": 4.68,
            "Dwellings": -7.92,
            "Good intent": -11.42,
            "Malicious": 27.27,
            "Non-fire false alarms": -5.66,
            "Non-fire incidents": 15.85,
            "Other Buildings": 18.38,
            "Other Outdoors": -23.6,
            "Road Vehicles": 16.67,
            "Secondary Fires": 1.0
        }
    },
    "Cleveland": {
        "2020": {
            "Due to apparatus": 1002,
            "Dwellings": 233,
            "Good intent": 1686,
            "Malicious": 87,
            "Non-fire false alarms": 51,
            "Non-fire incidents": 1148,
            "Other Buildings": 170,
            "Other Outdoors": 51,
            "Road Vehicles": 287,
            "Secondary Fires": 3018,
            "Chimney Fires": 4
        },
        "2021": {
            "Chimney Fires": 17,
            "Due to apparatus": 1001,
            "Dwellings": 269,
            "Good intent": 1854,
            "Malicious": 127,
            "Non-fire false alarms": 59,
            "Non-fire incidents": 1645,
            "Other Buildings": 175,
            "Other Outdoors": 47,
            "Road Vehicles": 362,
            "Secondary Fires": 4315
        },
        "percentage_change": {
            "Chimney Fires": 325.0,
            "Due to apparatus": -0.1,
            "Dwellings": 15.45,
            "Good intent": 9.96,
            "Malicious": 45.98,
            "Non-fire false alarms": 15.69,
            "Non-fire incidents": 43.29,
            "Other Buildings": 2.94,
            "Other Outdoors": -7.84,
            "Road Vehicles": 26.13,
            "Secondary Fires": 42.98
        }
    },
    "Cornwall": {
        "2020": {
            "Chimney Fires": 107,
            "Due to apparatus": 1043,
            "Dwellings": 220,
            "Good intent": 1014,
            "Malicious": 44,
            "Non-fire false alarms": 92,
            "Non-fire incidents": 1507,
            "Other Buildings": 117,
            "Other Outdoors": 65,
            "Road Vehicles": 185,
            "Secondary Fires": 432
        },
        "2021": {
            "Chimney Fires": 90,
            "Due to apparatus": 1059,
            "Dwellings": 257,
            "Good intent": 808,
            "Malicious": 48,
            "Non-fire false alarms": 133,
            "Non-fire incidents": 2011,
            "Other Buildings": 135,
            "Other Outdoors": 91,
            "Road Vehicles": 201,
            "Secondary Fires": 579
        },
        "percentage_change": {
            "Chimney Fires": -15.89,
            "Due to apparatus": 1.53,
            "Dwellings": 16.82,
            "Good intent": -20.32,
            "Malicious": 9.09,
            "Non-fire false alarms": 44.57,
            "Non-fire incidents": 33.44,
            "Other Buildings": 15.38,
            "Other Outdoors": 40.0,
            "Road Vehicles": 8.65,
            "Secondary Fires": 34.03
        }
    },
    "Cumbria": {
        "2020": {
            "Chimney Fires": 97,
            "Due to apparatus": 887,
            "Dwellings": 251,
            "Good intent": 529,
            "Malicious": 42,
            "Non-fire false alarms": 67,
            "Non-fire incidents": 960,
            "Other Buildings": 139,
            "Other Outdoors": 70,
            "Road Vehicles": 169,
            "Secondary Fires": 732
        },
        "2021": {
            "Chimney Fires": 81,
            "Due to apparatus": 1104,
            "Dwellings": 240,
            "Good intent": 526,
            "Malicious": 61,
            "Non-fire false alarms": 77,
            "Non-fire incidents": 1366,
            "Other Buildings": 148,
            "Other Outdoors": 80,
            "Road Vehicles": 196,
            "Secondary Fires": 858
        },
        "percentage_change": {
            "Chimney Fires": -16.49,
            "Due to apparatus": 24.46,
            "Dwellings": -4.38,
            "Good intent": -0.57,
            "Malicious": 45.24,
            "Non-fire false alarms": 14.93,
            "Non-fire incidents": 42.29,
            "Other Buildings": 6.47,
            "Other Outdoors": 14.29,
            "Road Vehicles": 15.98,
            "Secondary Fires": 17.21
        }
    },
    "Derbyshire": {
        "2020": {
            "Chimney Fires": 71,
            "Due to apparatus": 1166,
            "Dwellings": 461,
            "Good intent": 1006,
            "Malicious": 62,
            "Non-fire false alarms": 46,
            "Non-fire incidents": 1272,
            "Other Buildings": 208,
            "Other Outdoors": 97,
            "Road Vehicles": 315,
            "Secondary Fires": 1161
        },
        "2021": {
            "Chimney Fires": 74,
            "Due to apparatus": 1663,
            "Dwellings": 414,
            "Good intent": 866,
            "Malicious": 94,
            "Non-fire false alarms": 46,
            "Non-fire incidents": 1710,
            "Other Buildings": 209,
            "Other Outdoors": 115,
            "Road Vehicles": 317,
            "Secondary Fires": 1303
        },
        "percentage_change": {
            "Chimney Fires": 4.23,
            "Due to apparatus": 42.62,
            "Dwellings": -10.2,
            "Good intent": -13.92,
            "Malicious": 51.61,
            "Non-fire false alarms": 0.0,
            "Non-fire incidents": 34.43,
            "Other Buildings": 0.48,
            "Other Outdoors": 18.56,
            "Road Vehicles": 0.63,
            "Secondary Fires": 12.23
        }
    },
    "Devon and Somerset": {
        "2020": {
            "Chimney Fires": 279,
            "Due to apparatus": 4097,
            "Dwellings": 866,
            "Good intent": 1662,
            "Malicious": 110,
            "Non-fire false alarms": 96,
            "Non-fire incidents": 4901,
            "Other Buildings": 385,
            "Other Outdoors": 129,
            "Road Vehicles": 562,
            "Secondary Fires": 1534
        },
        "2021": {
            "Chimney Fires": 227,
            "Due to apparatus": 4613,
            "Dwellings": 864,
            "Good intent": 1543,
            "Malicious": 122,
            "Non-fire false alarms": 87,
            "Non-fire incidents": 6535,
            "Other Buildings": 459,
            "Other Outdoors": 117,
            "Road Vehicles": 578,
            "Secondary Fires": 1463
        },
        "percentage_change": {
            "Chimney Fires": -18.64,
            "Due to apparatus": 12.59,
            "Dwellings": -0.23,
            "Good intent": -7.16,
            "Malicious": 10.91,
            "Non-fire false alarms": -9.38,
            "Non-fire incidents": 33.34,
            "Other Buildings": 19.22,
            "Other Outdoors": -9.3,
            "Road Vehicles": 2.85,
            "Secondary Fires": -4.63
        }
    },
    "Dorset and Wiltshire": {
        "2020": {
            "Chimney Fires": 173,
            "Due to apparatus": 3932,
            "Dwellings": 697,
            "Good intent": 2144,
            "Malicious": 132,
            "Non-fire false alarms": 208,
            "Non-fire incidents": 3443,
            "Other Buildings": 307,
            "Other Outdoors": 220,
            "Road Vehicles": 413,
            "Secondary Fires": 1548
        },
        "2021": {
            "Chimney Fires": 147,
            "Due to apparatus": 4275,
            "Dwellings": 727,
            "Good intent": 1851,
            "Malicious": 188,
            "Non-fire false alarms": 212,
            "Non-fire incidents": 4334,
            "Other Buildings": 389,
            "Other Outdoors": 185,
            "Road Vehicles": 358,
            "Secondary Fires": 1222
        },
        "percentage_change": {
            "Chimney Fires": -15.03,
            "Due to apparatus": 8.72,
            "Dwellings": 4.3,
            "Good intent": -13.67,
            "Malicious": 42.42,
            "Non-fire false alarms": 1.92,
            "Non-fire incidents": 25.88,
            "Other Buildings": 26.71,
            "Other Outdoors": -15.91,
            "Road Vehicles": -13.32,
            "Secondary Fires": -21.06
        }
    },
    "Durham": {
        "2020": {
            "Chimney Fires": 62,
            "Due to apparatus": 1012,
            "Dwellings": 271,
            "Good intent": 1314,
            "Malicious": 40,
            "Non-fire false alarms": 55,
            "Non-fire incidents": 956,
            "Other Buildings": 153,
            "Other Outdoors": 79,
            "Road Vehicles": 470,
            "Secondary Fires": 2336
        },
        "2021": {
            "Chimney Fires": 41,
            "Due to apparatus": 1172,
            "Dwellings": 257,
            "Good intent": 1241,
            "Malicious": 48,
            "Non-fire false alarms": 82,
            "Non-fire incidents": 1411,
            "Other Buildings": 187,
            "Other Outdoors": 80,
            "Road Vehicles": 449,
            "Secondary Fires": 3111
        },
        "percentage_change": {
            "Chimney Fires": -33.87,
            "Due to apparatus": 15.81,
            "Dwellings": -5.17,
            "Good intent": -5.56,
            "Malicious": 20.0,
            "Non-fire false alarms": 49.09,
            "Non-fire incidents": 47.59,
            "Other Buildings": 22.22,
            "Other Outdoors": 1.27,
            "Road Vehicles": -4.47,
            "Secondary Fires": 33.18
        }
    },
    "East Sussex": {
        "2020": {
            "Chimney Fires": 85,
            "Due to apparatus": 3137,
            "Dwellings": 486,
            "Good intent": 1262,
            "Malicious": 71,
            "Non-fire false alarms": 72,
            "Non-fire incidents": 3209,
            "Other Buildings": 197,
            "Other Outdoors": 118,
            "Road Vehicles": 201,
            "Secondary Fires": 902
        },
        "2021": {
            "Chimney Fires": 65,
            "Due to apparatus": 3540,
            "Dwellings": 474,
            "Good intent": 1114,
            "Malicious": 144,
            "Non-fire false alarms": 61,
            "Non-fire incidents": 3959,
            "Other Buildings": 190,
            "Other Outdoors": 119,
            "Road Vehicles": 187,
            "Secondary Fires": 815
        },
        "percentage_change": {
            "Chimney Fires": -23.53,
            "Due to apparatus": 12.85,
            "Dwellings": -2.47,
            "Good intent": -11.73,
            "Malicious": 102.82,
            "Non-fire false alarms": -15.28,
            "Non-fire incidents": 23.37,
            "Other Buildings": -3.55,
            "Other Outdoors": 0.85,
            "Road Vehicles": -6.97,
            "Secondary Fires": -9.65
        }
    },
    "Essex": {
        "2020": {
            "Chimney Fires": 61,
            "Due to apparatus": 2617,
            "Dwellings": 802,
            "Good intent": 3044,
            "Malicious": 143,
            "Non-fire false alarms": 270,
            "Non-fire incidents": 4105,
            "Other Buildings": 344,
            "Other Outdoors": 201,
            "Road Vehicles": 576,
            "Secondary Fires": 2246
        },
        "2021": {
            "Chimney Fires": 56,
            "Due to apparatus": 2953,
            "Dwellings": 789,
            "Good intent": 2955,
            "Malicious": 177,
            "Non-fire false alarms": 410,
            "Non-fire incidents": 5246,
            "Other Buildings": 387,
            "Other Outdoors": 167,
            "Road Vehicles": 593,
            "Secondary Fires": 1776
        },
        "percentage_change": {
            "Chimney Fires": -8.2,
            "Due to apparatus": 12.84,
            "Dwellings": -1.62,
            "Good intent": -2.92,
            "Malicious": 23.78,
            "Non-fire false alarms": 51.85,
            "Non-fire incidents": 27.8,
            "Other Buildings": 12.5,
            "Other Outdoors": -16.92,
            "Road Vehicles": 2.95,
            "Secondary Fires": -20.93
        }
    },
    "Gloucestershire": {
        "2020": {
            "Chimney Fires": 80,
            "Due to apparatus": 913,
            "Dwellings": 260,
            "Good intent": 803,
            "Malicious": 28,
            "Non-fire false alarms": 71,
            "Non-fire incidents": 1976,
            "Other Buildings": 119,
            "Other Outdoors": 63,
            "Road Vehicles": 169,
            "Secondary Fires": 608
        },
        "2021": {
            "Chimney Fires": 85,
            "Due to apparatus": 1027,
            "Dwellings": 290,
            "Good intent": 774,
            "Malicious": 32,
            "Non-fire false alarms": 65,
            "Non-fire incidents": 2689,
            "Other Buildings": 129,
            "Other Outdoors": 57,
            "Road Vehicles": 216,
            "Secondary Fires": 604
        },
        "percentage_change": {
            "Chimney Fires": 6.25,
            "Due to apparatus": 12.49,
            "Dwellings": 11.54,
            "Good intent": -3.61,
            "Malicious": 14.29,
            "Non-fire false alarms": -8.45,
            "Non-fire incidents": 36.08,
            "Other Buildings": 8.4,
            "Other Outdoors": -9.52,
            "Road Vehicles": 27.81,
            "Secondary Fires": -0.66
        }
    },
    "Greater London": {
        "2020": {
            "Chimney Fires": 19,
            "Due to apparatus": 36440,
            "Dwellings": 4958,
            "Good intent": 9693,
            "Malicious": 786,
            "Non-fire false alarms": 1810,
            "Non-fire incidents": 31014,
            "Other Buildings": 1562,
            "Other Outdoors": 543,
            "Road Vehicles": 1374,
            "Secondary Fires": 8503
        },
        "2021": {
            "Chimney Fires": 14,
            "Due to apparatus": 43859,
            "Dwellings": 4918,
            "Good intent": 8653,
            "Malicious": 861,
            "Non-fire false alarms": 2185,
            "Non-fire incidents": 43775,
            "Other Buildings": 1684,
            "Other Outdoors": 440,
            "Road Vehicles": 1438,
            "Secondary Fires": 6826
        },
        "percentage_change": {
            "Chimney Fires": -26.32,
            "Due to apparatus": 20.36,
            "Dwellings": -0.81,
            "Good intent": -10.73,
            "Malicious": 9.54,
            "Non-fire false alarms": 20.72,
            "Non-fire incidents": 41.15,
            "Other Buildings": 7.81,
            "Other Outdoors": -18.97,
            "Road Vehicles": 4.66,
            "Secondary Fires": -19.72
        }
    },
    "Greater Manchester": {
        "2020": {
            "Chimney Fires": 44,
            "Due to apparatus": 8140,
            "Dwellings": 1876,
            "Good intent": 3498,
            "Malicious": 418,
            "Non-fire false alarms": 314,
            "Non-fire incidents": 4913,
            "Other Buildings": 817,
            "Other Outdoors": 188,
            "Road Vehicles": 1112,
            "Secondary Fires": 6482
        },
        "2021": {
            "Chimney Fires": 36,
            "Due to apparatus": 8879,
            "Dwellings": 1749,
            "Good intent": 2945,
            "Malicious": 557,
            "Non-fire false alarms": 478,
            "Non-fire incidents": 7013,
            "Other Buildings": 811,
            "Other Outdoors": 188,
            "Road Vehicles": 1217,
            "Secondary Fires": 6624
        },
        "percentage_change": {
            "Chimney Fires": -18.18,
            "Due to apparatus": 9.08,
            "Dwellings": -6.77,
            "Good intent": -15.81,
            "Malicious": 33.25,
            "Non-fire false alarms": 52.23,
            "Non-fire incidents": 42.74,
            "Other Buildings": -0.73,
            "Other Outdoors": 0.0,
            "Road Vehicles": 9.44,
            "Secondary Fires": 2.19
        }
    },
    "Hampshire and Isle of Wight": {
        "2020": {
            "Chimney Fires": 148,
            "Due to apparatus": 4946,
            "Dwellings": 798,
            "Good intent": 2405,
            "Malicious": 211,
            "Non-fire false alarms": 224,
            "Non-fire incidents": 4277,
            "Other Buildings": 371,
            "Other Outdoors": 416,
            "Road Vehicles": 531,
            "Secondary Fires": 2038
        },
        "2021": {
            "Chimney Fires": 99,
            "Due to apparatus": 5600,
            "Dwellings": 897,
            "Good intent": 2268,
            "Malicious": 280,
            "Non-fire false alarms": 217,
            "Non-fire incidents": 4451,
            "Other Buildings": 360,
            "Other Outdoors": 357,
            "Road Vehicles": 576,
            "Secondary Fires": 1660
        },
        "percentage_change": {
            "Chimney Fires": -33.11,
            "Due to apparatus": 13.22,
            "Dwellings": 12.41,
            "Good intent": -5.7,
            "Malicious": 32.7,
            "Non-fire false alarms": -3.12,
            "Non-fire incidents": 4.07,
            "Other Buildings": -2.96,
            "Other Outdoors": -14.18,
            "Road Vehicles": 8.47,
            "Secondary Fires": -18.55
        }
    },
    "Hereford and Worcester": {
        "2020": {
            "Chimney Fires": 114,
            "Due to apparatus": 2398,
            "Dwellings": 334,
            "Good intent": 869,
            "Malicious": 32,
            "Non-fire false alarms": 69,
            "Non-fire incidents": 2027,
            "Other Buildings": 167,
            "Other Outdoors": 129,
            "Road Vehicles": 203,
            "Secondary Fires": 747
        },
        "2021": {
            "Chimney Fires": 72,
            "Due to apparatus": 2567,
            "Dwellings": 362,
            "Good intent": 734,
            "Malicious": 59,
            "Non-fire false alarms": 87,
            "Non-fire incidents": 2408,
            "Other Buildings": 175,
            "Other Outdoors": 112,
            "Road Vehicles": 229,
            "Secondary Fires": 674
        },
        "percentage_change": {
            "Chimney Fires": -36.84,
            "Due to apparatus": 7.05,
            "Dwellings": 8.38,
            "Good intent": -15.54,
            "Malicious": 84.38,
            "Non-fire false alarms": 26.09,
            "Non-fire incidents": 18.8,
            "Other Buildings": 4.79,
            "Other Outdoors": -13.18,
            "Road Vehicles": 12.81,
            "Secondary Fires": -9.77
        }
    },
    "Hertfordshire": {
        "2020": {
            "Chimney Fires": 47,
            "Due to apparatus": 2583,
            "Dwellings": 464,
            "Good intent": 1752,
            "Malicious": 60,
            "Non-fire false alarms": 215,
            "Non-fire incidents": 2765,
            "Other Buildings": 172,
            "Other Outdoors": 183,
            "Road Vehicles": 315,
            "Secondary Fires": 1259
        },
        "2021": {
            "Chimney Fires": 36,
            "Due to apparatus": 2445,
            "Dwellings": 462,
            "Good intent": 1589,
            "Malicious": 91,
            "Non-fire false alarms": 326,
            "Non-fire incidents": 3709,
            "Other Buildings": 203,
            "Other Outdoors": 112,
            "Road Vehicles": 293,
            "Secondary Fires": 969
        },
        "percentage_change": {
            "Chimney Fires": -23.4,
            "Due to apparatus": -5.34,
            "Dwellings": -0.43,
            "Good intent": -9.3,
            "Malicious": 51.67,
            "Non-fire false alarms": 51.63,
            "Non-fire incidents": 34.14,
            "Other Buildings": 18.02,
            "Other Outdoors": -38.8,
            "Road Vehicles": -6.98,
            "Secondary Fires": -23.03
        }
    },
    "Humberside": {
        "2020": {
            "Chimney Fires": 64,
            "Due to apparatus": 2386,
            "Dwellings": 431,
            "Good intent": 1314,
            "Malicious": 82,
            "Non-fire false alarms": 46,
            "Non-fire incidents": 4820,
            "Other Buildings": 271,
            "Other Outdoors": 86,
            "Road Vehicles": 314,
            "Secondary Fires": 2175
        },
        "2021": {
            "Chimney Fires": 63,
            "Due to apparatus": 2435,
            "Dwellings": 449,
            "Good intent": 1062,
            "Malicious": 133,
            "Non-fire false alarms": 46,
            "Non-fire incidents": 5788,
            "Other Buildings": 240,
            "Other Outdoors": 97,
            "Road Vehicles": 423,
            "Secondary Fires": 2702
        },
        "percentage_change": {
            "Chimney Fires": -1.56,
            "Due to apparatus": 2.05,
            "Dwellings": 4.18,
            "Good intent": -19.18,
            "Malicious": 62.2,
            "Non-fire false alarms": 0.0,
            "Non-fire incidents": 20.08,
            "Other Buildings": -11.44,
            "Other Outdoors": 12.79,
            "Road Vehicles": 34.71,
            "Secondary Fires": 24.23
        }
    },
    "Isles Of Scilly": {
        "2020": {
            "Good intent": 2,
            "Non-fire incidents": 5,
            "Other Buildings": 1,
            "Other Outdoors": 1,
            "Secondary Fires": 3,
            "Due to apparatus": 2,
            "Non-fire false alarms": 1
        },
        "2021": {
            "Due to apparatus": 4,
            "Good intent": 8,
            "Non-fire incidents": 9,
            "Other Outdoors": 1,
            "Secondary Fires": 2,
            "Non-fire false alarms": 1,
            "Other Buildings": 2,
            "Chimney Fires": 1,
            "Dwellings": 1
        },
        "percentage_change": {
            "Due to apparatus": 100.0,
            "Good intent": 300.0,
            "Non-fire incidents": 80.0,
            "Other Outdoors": 0.0,
            "Secondary Fires": -33.33,
            "Non-fire false alarms": 0.0,
            "Other Buildings": 100.0,
            "Chimney Fires": 0,
            "Dwellings": 0
        }
    },
    "Kent": {
        "2020": {
            "Chimney Fires": 122,
            "Due to apparatus": 2118,
            "Dwellings": 599,
            "Good intent": 2754,
            "Malicious": 62,
            "Non-fire false alarms": 178,
            "Non-fire incidents": 8191,
            "Other Buildings": 357,
            "Other Outdoors": 178,
            "Road Vehicles": 698,
            "Secondary Fires": 2489
        },
        "2021": {
            "Chimney Fires": 110,
            "Due to apparatus": 2484,
            "Dwellings": 598,
            "Good intent": 2357,
            "Malicious": 63,
            "Non-fire false alarms": 220,
            "Non-fire incidents": 10903,
            "Other Buildings": 332,
            "Other Outdoors": 137,
            "Road Vehicles": 610,
            "Secondary Fires": 1892
        },
        "percentage_change": {
            "Chimney Fires": -9.84,
            "Due to apparatus": 17.28,
            "Dwellings": -0.17,
            "Good intent": -14.42,
            "Malicious": 1.61,
            "Non-fire false alarms": 23.6,
            "Non-fire incidents": 33.11,
            "Other Buildings": -7.0,
            "Other Outdoors": -23.03,
            "Road Vehicles": -12.61,
            "Secondary Fires": -23.99
        }
    },
    "Lancashire": {
        "2020": {
            "Chimney Fires": 86,
            "Due to apparatus": 4927,
            "Dwellings": 974,
            "Good intent": 3024,
            "Malicious": 266,
            "Non-fire false alarms": 307,
            "Non-fire incidents": 3821,
            "Other Buildings": 426,
            "Other Outdoors": 89,
            "Road Vehicles": 443,
            "Secondary Fires": 3207
        },
        "2021": {
            "Chimney Fires": 60,
            "Due to apparatus": 5890,
            "Dwellings": 948,
            "Good intent": 2529,
            "Malicious": 346,
            "Non-fire false alarms": 313,
            "Non-fire incidents": 4796,
            "Other Buildings": 485,
            "Other Outdoors": 73,
            "Road Vehicles": 459,
            "Secondary Fires": 3348
        },
        "percentage_change": {
            "Chimney Fires": -30.23,
            "Due to apparatus": 19.55,
            "Dwellings": -2.67,
            "Good intent": -16.37,
            "Malicious": 30.08,
            "Non-fire false alarms": 1.95,
            "Non-fire incidents": 25.52,
            "Other Buildings": 13.85,
            "Other Outdoors": -17.98,
            "Road Vehicles": 3.61,
            "Secondary Fires": 4.4
        }
    },
    "Leicestershire": {
        "2020": {
            "Chimney Fires": 55,
            "Due to apparatus": 1370,
            "Dwellings": 391,
            "Good intent": 1307,
            "Malicious": 83,
            "Non-fire false alarms": 101,
            "Non-fire incidents": 2807,
            "Other Buildings": 220,
            "Other Outdoors": 77,
            "Road Vehicles": 308,
            "Secondary Fires": 907
        },
        "2021": {
            "Chimney Fires": 57,
            "Due to apparatus": 1484,
            "Dwellings": 390,
            "Good intent": 1328,
            "Malicious": 91,
            "Non-fire false alarms": 133,
            "Non-fire incidents": 3259,
            "Other Buildings": 226,
            "Other Outdoors": 76,
            "Road Vehicles": 359,
            "Secondary Fires": 861
        },
        "percentage_change": {
            "Chimney Fires": 3.64,
            "Due to apparatus": 8.32,
            "Dwellings": -0.26,
            "Good intent": 1.61,
            "Malicious": 9.64,
            "Non-fire false alarms": 31.68,
            "Non-fire incidents": 16.1,
            "Other Buildings": 2.73,
            "Other Outdoors": -1.3,
            "Road Vehicles": 16.56,
            "Secondary Fires": -5.07
        }
    },
    "Lincolnshire": {
        "2020": {
            "Chimney Fires": 65,
            "Due to apparatus": 1155,
            "Dwellings": 361,
            "Good intent": 892,
            "Malicious": 35,
            "Non-fire incidents": 4190,
            "Other Buildings": 215,
            "Other Outdoors": 80,
            "Road Vehicles": 291,
            "Secondary Fires": 732,
            "Non-fire false alarms": 14
        },
        "2021": {
            "Chimney Fires": 45,
            "Due to apparatus": 1284,
            "Dwellings": 356,
            "Good intent": 820,
            "Malicious": 49,
            "Non-fire false alarms": 28,
            "Non-fire incidents": 4079,
            "Other Buildings": 234,
            "Other Outdoors": 104,
            "Road Vehicles": 275,
            "Secondary Fires": 758
        },
        "percentage_change": {
            "Chimney Fires": -30.77,
            "Due to apparatus": 11.17,
            "Dwellings": -1.39,
            "Good intent": -8.07,
            "Malicious": 40.0,
            "Non-fire false alarms": 100.0,
            "Non-fire incidents": -2.65,
            "Other Buildings": 8.84,
            "Other Outdoors": 30.0,
            "Road Vehicles": -5.5,
            "Secondary Fires": 3.55
        }
    },
    "Merseyside": {
        "2020": {
            "Chimney Fires": 22,
            "Due to apparatus": 3340,
            "Dwellings": 955,
            "Good intent": 1933,
            "Malicious": 125,
            "Non-fire false alarms": 81,
            "Non-fire incidents": 4253,
            "Other Buildings": 238,
            "Other Outdoors": 108,
            "Road Vehicles": 475,
            "Secondary Fires": 4354
        },
        "2021": {
            "Chimney Fires": 14,
            "Due to apparatus": 3515,
            "Dwellings": 980,
            "Good intent": 2070,
            "Malicious": 184,
            "Non-fire false alarms": 269,
            "Non-fire incidents": 5355,
            "Other Buildings": 279,
            "Other Outdoors": 124,
            "Road Vehicles": 613,
            "Secondary Fires": 4920
        },
        "percentage_change": {
            "Chimney Fires": -36.36,
            "Due to apparatus": 5.24,
            "Dwellings": 2.62,
            "Good intent": 7.09,
            "Malicious": 47.2,
            "Non-fire false alarms": 232.1,
            "Non-fire incidents": 25.91,
            "Other Buildings": 17.23,
            "Other Outdoors": 14.81,
            "Road Vehicles": 29.05,
            "Secondary Fires": 13.0
        }
    },
    "Norfolk": {
        "2020": {
            "Chimney Fires": 105,
            "Due to apparatus": 1366,
            "Dwellings": 428,
            "Good intent": 1007,
            "Malicious": 58,
            "Non-fire false alarms": 73,
            "Non-fire incidents": 2945,
            "Other Buildings": 215,
            "Other Outdoors": 181,
            "Road Vehicles": 261,
            "Secondary Fires": 878
        },
        "2021": {
            "Chimney Fires": 85,
            "Due to apparatus": 1653,
            "Dwellings": 396,
            "Good intent": 878,
            "Malicious": 68,
            "Non-fire false alarms": 73,
            "Non-fire incidents": 2921,
            "Other Buildings": 275,
            "Other Outdoors": 135,
            "Road Vehicles": 262,
            "Secondary Fires": 753
        },
        "percentage_change": {
            "Chimney Fires": -19.05,
            "Due to apparatus": 21.01,
            "Dwellings": -7.48,
            "Good intent": -12.81,
            "Malicious": 17.24,
            "Non-fire false alarms": 0.0,
            "Non-fire incidents": -0.81,
            "Other Buildings": 27.91,
            "Other Outdoors": -25.41,
            "Road Vehicles": 0.38,
            "Secondary Fires": -14.24
        }
    },
    "North Yorkshire": {
        "2020": {
            "Chimney Fires": 126,
            "Due to apparatus": 2242,
            "Dwellings": 308,
            "Good intent": 725,
            "Malicious": 67,
            "Non-fire false alarms": 79,
            "Non-fire incidents": 1671,
            "Other Buildings": 213,
            "Other Outdoors": 155,
            "Road Vehicles": 206,
            "Secondary Fires": 700
        },
        "2021": {
            "Chimney Fires": 94,
            "Due to apparatus": 2433,
            "Dwellings": 324,
            "Good intent": 748,
            "Malicious": 93,
            "Non-fire false alarms": 105,
            "Non-fire incidents": 2589,
            "Other Buildings": 206,
            "Other Outdoors": 144,
            "Road Vehicles": 269,
            "Secondary Fires": 713
        },
        "percentage_change": {
            "Chimney Fires": -25.4,
            "Due to apparatus": 8.52,
            "Dwellings": 5.19,
            "Good intent": 3.17,
            "Malicious": 38.81,
            "Non-fire false alarms": 32.91,
            "Non-fire incidents": 54.94,
            "Other Buildings": -3.29,
            "Other Outdoors": -7.1,
            "Road Vehicles": 30.58,
            "Secondary Fires": 1.86
        }
    },
    "Northamptonshire": {
        "2020": {
            "Chimney Fires": 47,
            "Due to apparatus": 653,
            "Dwellings": 342,
            "Good intent": 972,
            "Malicious": 67,
            "Non-fire false alarms": 58,
            "Non-fire incidents": 1577,
            "Other Buildings": 159,
            "Other Outdoors": 103,
            "Road Vehicles": 222,
            "Secondary Fires": 665
        },
        "2021": {
            "Chimney Fires": 45,
            "Due to apparatus": 818,
            "Dwellings": 351,
            "Good intent": 929,
            "Malicious": 84,
            "Non-fire false alarms": 64,
            "Non-fire incidents": 1855,
            "Other Buildings": 196,
            "Other Outdoors": 131,
            "Road Vehicles": 225,
            "Secondary Fires": 753
        },
        "percentage_change": {
            "Chimney Fires": -4.26,
            "Due to apparatus": 25.27,
            "Dwellings": 2.63,
            "Good intent": -4.42,
            "Malicious": 25.37,
            "Non-fire false alarms": 10.34,
            "Non-fire incidents": 17.63,
            "Other Buildings": 23.27,
            "Other Outdoors": 27.18,
            "Road Vehicles": 1.35,
            "Secondary Fires": 13.23
        }
    },
    "Northumberland": {
        "2020": {
            "Chimney Fires": 54,
            "Due to apparatus": 702,
            "Dwellings": 146,
            "Good intent": 386,
            "Malicious": 19,
            "Non-fire false alarms": 16,
            "Non-fire incidents": 552,
            "Other Buildings": 80,
            "Other Outdoors": 47,
            "Road Vehicles": 141,
            "Secondary Fires": 851
        },
        "2021": {
            "Chimney Fires": 47,
            "Due to apparatus": 842,
            "Dwellings": 146,
            "Good intent": 356,
            "Malicious": 31,
            "Non-fire false alarms": 10,
            "Non-fire incidents": 920,
            "Other Buildings": 112,
            "Other Outdoors": 56,
            "Road Vehicles": 150,
            "Secondary Fires": 1153
        },
        "percentage_change": {
            "Chimney Fires": -12.96,
            "Due to apparatus": 19.94,
            "Dwellings": 0.0,
            "Good intent": -7.77,
            "Malicious": 63.16,
            "Non-fire false alarms": -37.5,
            "Non-fire incidents": 66.67,
            "Other Buildings": 40.0,
            "Other Outdoors": 19.15,
            "Road Vehicles": 6.38,
            "Secondary Fires": 35.49
        }
    },
    "Nottinghamshire": {
        "2020": {
            "Chimney Fires": 54,
            "Due to apparatus": 2668,
            "Dwellings": 583,
            "Good intent": 1019,
            "Malicious": 103,
            "Non-fire false alarms": 41,
            "Non-fire incidents": 2244,
            "Other Buildings": 249,
            "Other Outdoors": 120,
            "Road Vehicles": 359,
            "Secondary Fires": 1588
        },
        "2021": {
            "Chimney Fires": 38,
            "Due to apparatus": 2967,
            "Dwellings": 640,
            "Good intent": 967,
            "Malicious": 133,
            "Non-fire false alarms": 67,
            "Non-fire incidents": 2594,
            "Other Buildings": 290,
            "Other Outdoors": 142,
            "Road Vehicles": 386,
            "Secondary Fires": 1904
        },
        "percentage_change": {
            "Chimney Fires": -29.63,
            "Due to apparatus": 11.21,
            "Dwellings": 9.78,
            "Good intent": -5.1,
            "Malicious": 29.13,
            "Non-fire false alarms": 63.41,
            "Non-fire incidents": 15.6,
            "Other Buildings": 16.47,
            "Other Outdoors": 18.33,
            "Road Vehicles": 7.52,
            "Secondary Fires": 19.9
        }
    },
    "Oxfordshire": {
        "2020": {
            "Chimney Fires": 80,
            "Due to apparatus": 2110,
            "Dwellings": 280,
            "Good intent": 561,
            "Malicious": 23,
            "Non-fire false alarms": 72,
            "Non-fire incidents": 1408,
            "Other Buildings": 127,
            "Other Outdoors": 69,
            "Road Vehicles": 194,
            "Secondary Fires": 552
        },
        "2021": {
            "Chimney Fires": 74,
            "Due to apparatus": 2371,
            "Dwellings": 286,
            "Good intent": 556,
            "Malicious": 45,
            "Non-fire false alarms": 63,
            "Non-fire incidents": 1820,
            "Other Buildings": 148,
            "Other Outdoors": 81,
            "Road Vehicles": 180,
            "Secondary Fires": 497
        },
        "percentage_change": {
            "Chimney Fires": -7.5,
            "Due to apparatus": 12.37,
            "Dwellings": 2.14,
            "Good intent": -0.89,
            "Malicious": 95.65,
            "Non-fire false alarms": -12.5,
            "Non-fire incidents": 29.26,
            "Other Buildings": 16.54,
            "Other Outdoors": 17.39,
            "Road Vehicles": -7.22,
            "Secondary Fires": -9.96
        }
    },
    "Shropshire": {
        "2020": {
            "Chimney Fires": 72,
            "Due to apparatus": 1145,
            "Dwellings": 218,
            "Good intent": 342,
            "Malicious": 35,
            "Non-fire false alarms": 16,
            "Non-fire incidents": 1102,
            "Other Buildings": 157,
            "Other Outdoors": 27,
            "Road Vehicles": 149,
            "Secondary Fires": 531
        },
        "2021": {
            "Chimney Fires": 59,
            "Due to apparatus": 1187,
            "Dwellings": 193,
            "Good intent": 261,
            "Malicious": 38,
            "Non-fire false alarms": 25,
            "Non-fire incidents": 1134,
            "Other Buildings": 145,
            "Other Outdoors": 25,
            "Road Vehicles": 159,
            "Secondary Fires": 457
        },
        "percentage_change": {
            "Chimney Fires": -18.06,
            "Due to apparatus": 3.67,
            "Dwellings": -11.47,
            "Good intent": -23.68,
            "Malicious": 8.57,
            "Non-fire false alarms": 56.25,
            "Non-fire incidents": 2.9,
            "Other Buildings": -7.64,
            "Other Outdoors": -7.41,
            "Road Vehicles": 6.71,
            "Secondary Fires": -13.94
        }
    },
    "South Yorkshire": {
        "2020": {
            "Chimney Fires": 24,
            "Due to apparatus": 1201,
            "Dwellings": 622,
            "Good intent": 2341,
            "Malicious": 70,
            "Non-fire false alarms": 170,
            "Non-fire incidents": 2395,
            "Other Buildings": 340,
            "Other Outdoors": 113,
            "Road Vehicles": 890,
            "Secondary Fires": 4078
        },
        "2021": {
            "Chimney Fires": 28,
            "Due to apparatus": 1921,
            "Dwellings": 762,
            "Good intent": 1794,
            "Malicious": 143,
            "Non-fire false alarms": 146,
            "Non-fire incidents": 3318,
            "Other Buildings": 390,
            "Other Outdoors": 134,
            "Road Vehicles": 954,
            "Secondary Fires": 4365
        },
        "percentage_change": {
            "Chimney Fires": 16.67,
            "Due to apparatus": 59.95,
            "Dwellings": 22.51,
            "Good intent": -23.37,
            "Malicious": 104.29,
            "Non-fire false alarms": -14.12,
            "Non-fire incidents": 38.54,
            "Other Buildings": 14.71,
            "Other Outdoors": 18.58,
            "Road Vehicles": 7.19,
            "Secondary Fires": 7.04
        }
    },
    "Staffordshire": {
        "2020": {
            "Chimney Fires": 76,
            "Due to apparatus": 1412,
            "Dwellings": 567,
            "Good intent": 1452,
            "Malicious": 68,
            "Non-fire false alarms": 75,
            "Non-fire incidents": 1672,
            "Other Buildings": 270,
            "Other Outdoors": 79,
            "Road Vehicles": 366,
            "Secondary Fires": 1813
        },
        "2021": {
            "Chimney Fires": 66,
            "Due to apparatus": 1572,
            "Dwellings": 505,
            "Good intent": 1272,
            "Malicious": 79,
            "Non-fire false alarms": 87,
            "Non-fire incidents": 2104,
            "Other Buildings": 346,
            "Other Outdoors": 62,
            "Road Vehicles": 374,
            "Secondary Fires": 1619
        },
        "percentage_change": {
            "Chimney Fires": -13.16,
            "Due to apparatus": 11.33,
            "Dwellings": -10.93,
            "Good intent": -12.4,
            "Malicious": 16.18,
            "Non-fire false alarms": 16.0,
            "Non-fire incidents": 25.84,
            "Other Buildings": 28.15,
            "Other Outdoors": -21.52,
            "Road Vehicles": 2.19,
            "Secondary Fires": -10.7
        }
    },
    "Suffolk": {
        "2020": {
            "Chimney Fires": 93,
            "Due to apparatus": 1582,
            "Dwellings": 284,
            "Good intent": 817,
            "Malicious": 51,
            "Non-fire false alarms": 19,
            "Non-fire incidents": 1107,
            "Other Buildings": 196,
            "Other Outdoors": 62,
            "Road Vehicles": 212,
            "Secondary Fires": 886
        },
        "2021": {
            "Chimney Fires": 63,
            "Due to apparatus": 1744,
            "Dwellings": 338,
            "Good intent": 741,
            "Malicious": 71,
            "Non-fire false alarms": 18,
            "Non-fire incidents": 1398,
            "Other Buildings": 169,
            "Other Outdoors": 61,
            "Road Vehicles": 183,
            "Secondary Fires": 639
        },
        "percentage_change": {
            "Chimney Fires": -32.26,
            "Due to apparatus": 10.24,
            "Dwellings": 19.01,
            "Good intent": -9.3,
            "Malicious": 39.22,
            "Non-fire false alarms": -5.26,
            "Non-fire incidents": 26.29,
            "Other Buildings": -13.78,
            "Other Outdoors": -1.61,
            "Road Vehicles": -13.68,
            "Secondary Fires": -27.88
        }
    },
    "Surrey": {
        "2020": {
            "Chimney Fires": 70,
            "Due to apparatus": 3009,
            "Dwellings": 459,
            "Good intent": 1435,
            "Malicious": 53,
            "Non-fire false alarms": 31,
            "Non-fire incidents": 2819,
            "Other Buildings": 215,
            "Other Outdoors": 111,
            "Road Vehicles": 323,
            "Secondary Fires": 1349
        },
        "2021": {
            "Chimney Fires": 64,
            "Due to apparatus": 3586,
            "Dwellings": 486,
            "Good intent": 1194,
            "Malicious": 61,
            "Non-fire false alarms": 34,
            "Non-fire incidents": 3797,
            "Other Buildings": 250,
            "Other Outdoors": 71,
            "Road Vehicles": 349,
            "Secondary Fires": 864
        },
        "percentage_change": {
            "Chimney Fires": -8.57,
            "Due to apparatus": 19.18,
            "Dwellings": 5.88,
            "Good intent": -16.79,
            "Malicious": 15.09,
            "Non-fire false alarms": 9.68,
            "Non-fire incidents": 34.69,
            "Other Buildings": 16.28,
            "Other Outdoors": -36.04,
            "Road Vehicles": 8.05,
            "Secondary Fires": -35.95
        }
    },
    "Tyne and Wear": {
        "2020": {
            "Due to apparatus": 3941,
            "Dwellings": 600,
            "Good intent": 2068,
            "Malicious": 141,
            "Non-fire false alarms": 33,
            "Non-fire incidents": 2441,
            "Other Buildings": 280,
            "Other Outdoors": 90,
            "Road Vehicles": 665,
            "Secondary Fires": 4896,
            "Chimney Fires": 13
        },
        "2021": {
            "Chimney Fires": 14,
            "Due to apparatus": 4118,
            "Dwellings": 579,
            "Good intent": 1941,
            "Malicious": 223,
            "Non-fire false alarms": 44,
            "Non-fire incidents": 3112,
            "Other Buildings": 306,
            "Other Outdoors": 112,
            "Road Vehicles": 743,
            "Secondary Fires": 6747
        },
        "percentage_change": {
            "Chimney Fires": 7.69,
            "Due to apparatus": 4.49,
            "Dwellings": -3.5,
            "Good intent": -6.14,
            "Malicious": 58.16,
            "Non-fire false alarms": 33.33,
            "Non-fire incidents": 27.49,
            "Other Buildings": 9.29,
            "Other Outdoors": 24.44,
            "Road Vehicles": 11.73,
            "Secondary Fires": 37.81
        }
    },
    "Warwickshire": {
        "2020": {
            "Chimney Fires": 39,
            "Due to apparatus": 725,
            "Dwellings": 108,
            "Good intent": 766,
            "Malicious": 13,
            "Non-fire false alarms": 100,
            "Non-fire incidents": 848,
            "Other Buildings": 82,
            "Other Outdoors": 95,
            "Road Vehicles": 201,
            "Secondary Fires": 540
        },
        "2021": {
            "Chimney Fires": 40,
            "Due to apparatus": 885,
            "Dwellings": 184,
            "Good intent": 628,
            "Malicious": 19,
            "Non-fire false alarms": 79,
            "Non-fire incidents": 1045,
            "Other Buildings": 94,
            "Other Outdoors": 77,
            "Road Vehicles": 195,
            "Secondary Fires": 466
        },
        "percentage_change": {
            "Chimney Fires": 2.56,
            "Due to apparatus": 22.07,
            "Dwellings": 70.37,
            "Good intent": -18.02,
            "Malicious": 46.15,
            "Non-fire false alarms": -21.0,
            "Non-fire incidents": 23.23,
            "Other Buildings": 14.63,
            "Other Outdoors": -18.95,
            "Road Vehicles": -2.99,
            "Secondary Fires": -13.7
        }
    },
    "West Midlands": {
        "2020": {
            "Chimney Fires": 24,
            "Due to apparatus": 5630,
            "Dwellings": 1794,
            "Good intent": 3075,
            "Malicious": 411,
            "Non-fire false alarms": 246,
            "Non-fire incidents": 6318,
            "Other Buildings": 650,
            "Other Outdoors": 113,
            "Road Vehicles": 1028,
            "Secondary Fires": 5989
        },
        "2021": {
            "Chimney Fires": 29,
            "Due to apparatus": 5929,
            "Dwellings": 1702,
            "Good intent": 2616,
            "Malicious": 405,
            "Non-fire false alarms": 287,
            "Non-fire incidents": 8057,
            "Other Buildings": 714,
            "Other Outdoors": 111,
            "Road Vehicles": 983,
            "Secondary Fires": 5311
        },
        "percentage_change": {
            "Chimney Fires": 20.83,
            "Due to apparatus": 5.31,
            "Dwellings": -5.13,
            "Good intent": -14.93,
            "Malicious": -1.46,
            "Non-fire false alarms": 16.67,
            "Non-fire incidents": 27.52,
            "Other Buildings": 9.85,
            "Other Outdoors": -1.77,
            "Road Vehicles": -4.38,
            "Secondary Fires": -11.32
        }
    },
    "West Sussex": {
        "2020": {
            "Chimney Fires": 92,
            "Due to apparatus": 3222,
            "Dwellings": 409,
            "Good intent": 963,
            "Malicious": 95,
            "Non-fire false alarms": 53,
            "Non-fire incidents": 2492,
            "Other Buildings": 152,
            "Other Outdoors": 200,
            "Road Vehicles": 210,
            "Secondary Fires": 789
        },
        "2021": {
            "Chimney Fires": 70,
            "Due to apparatus": 3479,
            "Dwellings": 379,
            "Good intent": 827,
            "Malicious": 124,
            "Non-fire false alarms": 36,
            "Non-fire incidents": 3125,
            "Other Buildings": 151,
            "Other Outdoors": 135,
            "Road Vehicles": 204,
            "Secondary Fires": 646
        },
        "percentage_change": {
            "Chimney Fires": -23.91,
            "Due to apparatus": 7.98,
            "Dwellings": -7.33,
            "Good intent": -14.12,
            "Malicious": 30.53,
            "Non-fire false alarms": -32.08,
            "Non-fire incidents": 25.4,
            "Other Buildings": -0.66,
            "Other Outdoors": -32.5,
            "Road Vehicles": -2.86,
            "Secondary Fires": -18.12
        }
    },
    "West Yorkshire": {
        "2020": {
            "Chimney Fires": 78,
            "Due to apparatus": 7101,
            "Dwellings": 1066,
            "Good intent": 2921,
            "Malicious": 264,
            "Non-fire false alarms": 524,
            "Non-fire incidents": 3756,
            "Other Buildings": 507,
            "Other Outdoors": 224,
            "Road Vehicles": 1121,
            "Secondary Fires": 6169
        },
        "2021": {
            "Chimney Fires": 66,
            "Due to apparatus": 7655,
            "Dwellings": 1070,
            "Good intent": 2630,
            "Malicious": 369,
            "Non-fire false alarms": 612,
            "Non-fire incidents": 4646,
            "Other Buildings": 522,
            "Other Outdoors": 215,
            "Road Vehicles": 1079,
            "Secondary Fires": 6157
        },
        "percentage_change": {
            "Chimney Fires": -15.38,
            "Due to apparatus": 7.8,
            "Dwellings": 0.38,
            "Good intent": -9.96,
            "Malicious": 39.77,
            "Non-fire false alarms": 16.79,
            "Non-fire incidents": 23.7,
            "Other Buildings": 2.96,
            "Other Outdoors": -4.02,
            "Road Vehicles": -3.75,
            "Secondary Fires": -0.19
        }
    },
    "uk_total": {
        "2020": {
            "Chimney Fires": 3104,
            "Due to apparatus": 140164,
            "Dwellings": 27017,
            "Good intent": 71191,
            "Malicious": 4814,
            "Non-fire false alarms": 6675,
            "Non-fire incidents": 144331,
            "Other Buildings": 11921,
            "Other Outdoors": 5455,
            "Road Vehicles": 17520,
            "Secondary Fires": 86078
        },
        "2021": {
            "Chimney Fires": 2608,
            "Due to apparatus": 159732,
            "Dwellings": 27169,
            "Good intent": 63866,
            "Malicious": 6268,
            "Non-fire false alarms": 8117,
            "Non-fire incidents": 186492,
            "Other Buildings": 12948,
            "Other Outdoors": 4997,
            "Road Vehicles": 18382,
            "Secondary Fires": 86525
        },
        "percentage_change": {
            "Chimney Fires": -15.98,
            "Due to apparatus": 13.96,
            "Dwellings": 0.56,
            "Good intent": -10.29,
            "Malicious": 30.2,
            "Non-fire false alarms": 21.6,
            "Non-fire incidents": 29.21,
            "Other Buildings": 8.62,
            "Other Outdoors": -8.4,
            "Road Vehicles": 4.92,
            "Secondary Fires": 0.52
        }
    }
}